### ISSUE TITLE
Current song is not updated when we pause and change it

### ISSUE THREAD

**Issue by PerseweratywneImponderabilia** [pywkm/ulauncher-spotify#1]
![image](https://user-images.githubusercontent.com/19861700/42322391-8f069b6c-805c-11e8-8f81-3811cb84535b.png)

When we pause our current song and then change it to the next one, the status still shows us the old song paused.

**Comment by pywkm** [comment]
Thank you for reporting! (my first issue in pet project ;)
It's strange, because I cannot reproduce it on my home computer (Mint 19 Cinnamon). It is, however, noticeable on my work machine (Ubuntu 18.04 Budgie) but only for the first time song is paused. Later seemed to work fine.
Do you experience that behavior every time you pause (and then choose "next"), or only the first time you do it? What OS (and DM) do you use?
I will investigate it, of course. :)

**Comment by PerseweratywneImponderabilia** [comment]
Manjaro KDE.

I've just noticed it doesn't happen every time. 1/3 or 1/4 times (seems like random; sometimes it works better most of the time, sometimes just the opposite) it reads the current song properly. Try to use the "sp next" option a few times, maybe you'll be able to reproduce it.
Also, sometimes when I keep changing the track (I spam it, the song lasts for max a second or two) the song just restarts once. It happens rarely though. Not sure if I should make a new issue for that, as it may be Spotify's issue and it's related to the reported bug.

Fortunately, it's just a small issue and the extension works great, thank you for your work. :)
