### ISSUE TITLE
Extension not working on ubuntu 21.10

### ISSUE THREAD

**Issue by Tyflomate** [pywkm/ulauncher-spotify#17]
Logs:
```
Message: 'com.github.pywkm.ulauncher-spotify'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.pywkm.ulauncher-spotify'

```
Screenshot:
![image](https://user-images.githubusercontent.com/76946195/160365744-ea9ad0ea-838a-4c48-a45d-ace90aaadc8d.png)

**Comment by Tyflomate** [comment]
@pywkm Help please :pray:

**Comment by pywkm** [comment]
@Tyflomate 
Oh, I will have to review my notifications settings here, because I didn't get one after issue was created. Only today after @ mention. I'm sorry for not responding.
Sure, will take a look at it. :)

**Comment by pywkm** [comment]
Honestly, stacktrace looks like error is in core Ulauncher app. Execution didn't even come to code of my extension.
I cannot reproduce this right now, well... I cannot even install my extension, because Ulauncher crashes on my distro (Mint 20.3 kernel 5.4.0-109) when I'm trying to open preferences. Great...

I'll try to install Ubuntu in VirtualBox and check it in free time, but it won't be quick and I cannot guarantee anything.
In the meantime you could try to report this issue to core Ulauncher maintainers. They made recently many breaking changes, from what I see.

**Comment by Tyflomate** [comment]
Alright, i'll try to see if there is any changes I must do on Ulauncher. I'll keep you posted thanks :+1:

**Comment by Tyflomate** [comment]
Ulauncher must have fixed this in an update, it works again !
